"""posts table

Revision ID: 995f83711805
Revises: 61d6a3ec9c4b
Create Date: 2018-02-25 19:33:11.191280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995f83711805'
down_revision = '61d6a3ec9c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
